// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ScriptText.Intake
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using General;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\M\source\repos\Project Assistant\ScriptText\Intake\LoadUnitDataIntake.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class LoadUnitDataIntake : LoadUnitDataIntakeBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("#include \"apdefap.h\"\r\n\r\nint gscAction( void )\r\n{\r\n\t// WINCC:TAGNAME_SECTION_START" +
                    "\r\n\t#define TagLoadData\t\t\"");
            
            #line 12 "C:\Users\M\source\repos\Project Assistant\ScriptText\Intake\LoadUnitDataIntake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UnitName));
            
            #line default
            #line hidden
            this.Write("-U.LoadData\"\r\n\t#define TagBatch\t\t\"");
            
            #line 13 "C:\Users\M\source\repos\Project Assistant\ScriptText\Intake\LoadUnitDataIntake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UnitName));
            
            #line default
            #line hidden
            this.Write("-U.Batch\"\r\n\t#define TagProdID\t\t\"");
            
            #line 14 "C:\Users\M\source\repos\Project Assistant\ScriptText\Intake\LoadUnitDataIntake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UnitName));
            
            #line default
            #line hidden
            this.Write("-U.ProdID\"\r\n\t#define TagSourceID\t\t\"");
            
            #line 15 "C:\Users\M\source\repos\Project Assistant\ScriptText\Intake\LoadUnitDataIntake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UnitName));
            
            #line default
            #line hidden
            this.Write("-P.SourceID\"\r\n\t#define TagSourceBin\t\"");
            
            #line 16 "C:\Users\M\source\repos\Project Assistant\ScriptText\Intake\LoadUnitDataIntake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UnitName));
            
            #line default
            #line hidden
            this.Write("-P.SB-Number\"\r\n\t#define TagCleaning\t\t\"");
            
            #line 17 "C:\Users\M\source\repos\Project Assistant\ScriptText\Intake\LoadUnitDataIntake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UnitName));
            
            #line default
            #line hidden
            this.Write("-P.Cleaning\"\r\n\t#define TagIntakeSpeed\t\"");
            
            #line 18 "C:\Users\M\source\repos\Project Assistant\ScriptText\Intake\LoadUnitDataIntake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UnitName));
            
            #line default
            #line hidden
            this.Write("-P.IT-Speed\"\r\n\t#define TagMagnet\t\t\"");
            
            #line 19 "C:\Users\M\source\repos\Project Assistant\ScriptText\Intake\LoadUnitDataIntake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UnitName));
            
            #line default
            #line hidden
            this.Write("-P.Magnet\"\r\n\t#define TagFineCleaning\t\"");
            
            #line 20 "C:\Users\M\source\repos\Project Assistant\ScriptText\Intake\LoadUnitDataIntake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UnitName));
            
            #line default
            #line hidden
            this.Write("-P.FineCleaning\"\r\n\t#define TagCOTime\t\t\"");
            
            #line 21 "C:\Users\M\source\repos\Project Assistant\ScriptText\Intake\LoadUnitDataIntake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UnitName));
            
            #line default
            #line hidden
            this.Write("-P.IT-CO-Time\"\r\n\t// WINCC:TAGNAME_SECTION_END\r\n\r\n\t#define PROFILE_ID\t\t");
            
            #line 24 "C:\Users\M\source\repos\Project Assistant\ScriptText\Intake\LoadUnitDataIntake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProfileId));
            
            #line default
            #line hidden
            this.Write("\r\n\t#define LINE_ID\t\t\t");
            
            #line 25 "C:\Users\M\source\repos\Project Assistant\ScriptText\Intake\LoadUnitDataIntake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LineId));
            
            #line default
            #line hidden
            this.Write(@"	// Intakeline ID
	#define LINE_CODE			0	// Default = 0. Can be used when parameters for multiple lines (%d in tagname)
	
	BOOL	bCleaning = FALSE, bMagnet = FALSE, bFineCleaning = FALSE;
	short	nSourceID = 0, nSourceBin = 0, nCOTime = 0;
	long	lProdID = 0;
	long	lBatchnumber = 0;
	float	fCap = 0, fSpeed = 0;
	char	szProdIDCode[16] = """";

	printf(""%s triggered... \r\n"", TagLoadData);

	if (GetTagBitWait(TagLoadData))
	{
		LoadITBatch(LINE_ID, &lBatchnumber, &lProdID, szProdIDCode, &nSourceID, &nSourceBin, &bCleaning, &fCap, &fSpeed, &bMagnet, &bFineCleaning, &nCOTime);

		if (lBatchnumber > 0 && lProdID > 0)
		{
			SetTagSDWordWait(TagProdID, lProdID);
			SetTagSDWordWait(TagBatch, lBatchnumber);
			SetTagSWordWait(TagSourceID, nSourceID);
			SetTagSWordWait(TagSourceBin, nSourceBin);
			SetTagBitWait(TagCleaning, (SHORT)bCleaning);
			SetTagFloatWait(TagIntakeSpeed, fSpeed);
			SetTagBitWait(TagMagnet, (SHORT)bMagnet);
			SetTagBitWait(TagFineCleaning, (SHORT)bFineCleaning);
			SetTagSWordWait(TagCOTime, nCOTime);
			
			if (lProdID == 0) SetTagSDWordWait(TagBatch, 0);

		      LoadLineConstants(LINE_ID, PROFILE_ID, LINE_CODE);
		}
		printf(""Executed\r\n"");

		SetTagBitWait(TagLoadData, FALSE);
	}

	return 0; 
}
");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 64 "C:\Users\M\source\repos\Project Assistant\ScriptText\Intake\LoadUnitDataIntake.tt"
 
public string UnitName = "EL01";
public int ProfileId = 101;
public int LineId = 101;
public CAction Action 
{
	get 
	{
		return new CAction() {
			Name = $"LoadUnitData{UnitName}",
			Source = this.TransformText(),
			Triggers = new List<string>() {
				$"{UnitName}-U.LoadData"
			},
			Path = $"Intake\\{UnitName}\\",
		};
	}
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class LoadUnitDataIntakeBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
